import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/containers/Navbar';
import BrandLogo from './components/icons/BrandLogo';
import MobileNavbar from './components/containers/MobileNavbar';
import NavLink from './components/ui/NavLink';
import ThemesProvider from '@/utils/contexts/ThemesProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang='en'
			className='dark'
			style={{ colorScheme: 'dark' }}>
			<body className=' bg-background'>
				<ThemesProvider>
					<Navbar
						brandIcon={
							<span className='md:text-7xl text-6xl w-full h-full text-text'>
								<BrandLogo />
							</span>
						}
						navLinks={[
							{ text: 'services', href: '/services' },
							{ text: 'about us', href: '/about-us' },
							{ text: 'contact', href: '#section-contact_form' },
						]}
						mobileNavbar={
							<MobileNavbar
								brandIcon={
									<span className='md:text-7xl text-6xl w-full h-full text-text'>
										<BrandLogo />
									</span>
								}
								navLinks={[
									{ text: 'contact', href: '/contact-us' },
									{ text: 'contact', href: '/contact-us' },
									{ text: 'contact', href: '/contact-us' },
								]}
							/>
						}
					/>
					{children}
				</ThemesProvider>
			</body>
		</html>
	);
}
